name: Auto Update M3U

on:
  schedule:
    - cron: '30 19 * * *'   # 1:00 AM IST = 19:30 UTC
  workflow_dispatch:        # manually bhi run kar sakte ho

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist"
          git push
