name: Auto Update M3U

on:
  schedule:
    - cron: '43 6 * * *'   # 12:13 PM IST = 06:43 UTC
  workflow_dispatch:        # manually bhi run kar sakte ho

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests cloudscraper

      - name: Run update script
        run: python nxt.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Aki.m3u
          git commit -m "Auto update playlist" || echo "No changes to commit"
          git push
